version: "3.1"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - reverse-proxy

  jenkins:
    build:
      context: . 
      dockerfile: Dockerfile 
    privileged: true
    user: root
    environment:
      - JENKINS_ARGS=--prefix=/jenkins
    volumes:
      - "jenkins_home:/var/jenkins_home"
    networks:
      - reverse-proxy

  sonarqube:
    image: sonarqube:latest
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    networks:
      - reverse-proxy
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - "postgresql:/var/lib/postgresql/data"
    networks:
      - reverse-proxy

volumes:
  jenkins_home:
  postgresql:

networks:
  reverse-proxy:
    driver: bridge
