pipeline {
    agent any
    options {
        timeout(time:30, unit: 'MINUTES')
    }
    environment {
        scannerHome = tool 'SonarQube'
    }
    stages {
        stage('Checkout repository') {
            steps {
                echo "Entering 'Checkout repository' stage"
                checkout scm
                echo "Completed 'Checkout repository' stage"
            }
        }

        stage('Check Current Directory') {
            steps {
                sh "ls -la"
            }
        }

        stage('OWASP Dependency-Check Vulnerabilities') {
            steps {
                dependencyCheck additionalArguments: ''' 
                            -o './'
                            -s './simple-app'
                            -f 'ALL' 
                            --prettyPrint''', odcInstallation: 'OWASP Dependency-Check Vulnerabilities'
                
                dependencyCheckPublisher pattern: 'dependency-check-report.xml'
            }
        }

        stage('Code Quality Check via SonarQube') {
            steps {
                 script {
                    // Define SonarQube Scanner
                    def sonarScannerHome = tool 'SonarQube';
                    env.PATH = "${sonarScannerHome}/bin:${env.PATH}"

                    // Execute SonarQube analysis
                    withSonarQubeEnv('SonarQube') {
                        sh """
                        sonar-scanner \
                        -Dsonar.projectKey=OWASP \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=http://sonarqube:9000 \
                        -Dsonar.login=sqp_391ea90ca5447812516cda004b73c1ad54166898
                        """
                    }
                }
            }
        }

        stage('Build and start docker images'){
            steps {
                sh "dockerd &"
                sh "docker --version"
                sh "docker-compose -f simple-app/docker-compose.yml down"
                sh "docker-compose -f simple-app/docker-compose.yml build"
                sh "docker-compose -f simple-app/docker-compose.yml up -d"
                sh "docker ps"
            }
        }

        stage('Run UI Tests') {
            steps {
                sh "python3 --version"
                sh "python3 -m pip install --user selenium==4.15.2"
                sh "python3 -m pip install --user selenium requests"
                sh "python3 ui-test/ui_tests.py"
            }
        }

        stage('Down docker images') {
            steps{
                sh "docker-compose -f simple-app/docker-compose.yml down -v"
            }
        }
    } 
}


